### PR TITLE
Update ukaz.tcl

### PR DESCRIPTION
**Pull request by Meshparts**
Changed format of tics option, which can now be auto, off, single positive float, pairs of label text and float (lists of two elements)

### CODE REVIEW

**Comment by auriocus** [comment]
It doesn't work for all intended cases. Try these in old ukaz:

```
(chris) 50 % package require ukaz
2.0a2
(chris) 51 % pack [ukaz::graph .g] -expand yes -fill both
(chris) 52 % set data {1 4.5 2 7.3 3 1.2 4 6.5}
.g plot $data with points

1 4.5 2 7.3 3 1.2 4 6.5
(chris) 53 % 0
(chris) 54 % .g set xtics 1.5 
(chris) 55 % .g set xtics Kartoffeln 1 2 2 Reis 3
(chris) 56 % 
```

With your pull request:

```
(ukaz-master) 50 % package require ukaz 2.1
2.1
(ukaz-master) 51 % pack [ukaz::graph .g] -expand yes -fill both
set data {1 4.5 2 7.3 3 1.2 4 6.5}
.g plot $data with points
(ukaz-master) 54 % .g set xtics 1.5 ;# works
(ukaz-master) 55 % .g set xtics 1 2 3 ;# error
can't read "pos": no such variable
(ukaz-master) 56 % .g set xtics {Kartoffeln 1} 2 {Nudeln 3} ;# hangs
```

**Comment by Meshparts** [comment]
I just fixed first of the two issues in your examples. 
The second issue ist unclear how to solve:
.g set xtics {Kartoffeln 1} 2 {Nudeln 3}
The above does not hangs but it leads to the error:
expected floating-point number but got "Kartoffeln"
Which I understand but how should the format command behave when mixed data is used? The default is %g but this cannot work in this case. Shold be the responsability of the user to specify a formatting command which can handle both strings and numbers?

**Comment by auriocus** [comment]
> The second issue ist unclear how to solve:
> .g set xtics {Kartoffeln 1} 2 {Nudeln 3}
> The above does not hangs but it leads to the error:
> expected floating-point number but got "Kartoffeln"
> Which I understand but how should the format command behave when mixed data is used?

It should, for every item in the list, check if it is a two-component list. If so, put a label with the string to the given position. If it is just one item, it is a number as usual and should be formatted with the standard formatter. 

The outcome should be the same as in the old ukaz with the line

```
.g set xtics Kartoffeln 1 [format %g 2] 2 Reis 3
```
Maybe leave the compute_ticlist as it was before and put this logic into parsetics, which can compute the list?

**Comment by auriocus** [comment]
PS: The hang seems to be a bug of Tk on macOS, when the error is thrown in the background.

**Comment by Meshparts** [comment]
Well, the old ukaz coul have a logical issue in the case

.g set xtics Kartoffeln 1 [format %g 2] 2 Reis 3
.g set ytics Kartoffeln 1 [format %g 2] 2 Reis 3

since there is also the option -xformat and -yformat which defaults to %g wich expects numbers.

So my idea is: Specifying non-numbers as tics and leaving the -?format options to their defaults could also be seen an usage issue. 

In cases where the tics are not numbers, the user should define another function that handles the format.

OR: ukaz should ignore non-numbers when applying the format command.

In any case: I don't like the idea, that the -?format option is ignored completly when the user specifies a list of tics.

I would prefer the solution, where ukaz only apply the format command to numbers.

**Comment by auriocus** [comment]
Maybe I was unclear - the idea is that, in case the label text is not specified, that the standard formatter (the one from the formatcommand option) provides the label text. If a label text is given, then that should be used. 
So, if -xformat is "%.2f" and the tics are set as:

`.g set xtics {Kartoffeln 1} 2 {Nudeln 3}`

then "Kartoffeln" should be written at position 1, "Nudeln" at position 3 and "2.00" at position 2 - because `format %.2f 2` is `2.00`

If there is an error - e.g. the item is `{Kartoffeln Nudeln}` (no position given) or `{Kartoffeln 2 3 4}` (superfluous items) or {"} (not a list), then the error should show up alread in the `set xtics` command.

**Comment by Meshparts** [comment]
ok, I hope I got it now. I'l make another commit.

**Comment by auriocus** [comment]
Everything works as intended; merged into the trunk. Thank you for the patch.

**Pull request merged**
